js/libs.js

requires https://github.com/Fliplet/fliplet-api/pull/2975

refactor to use new device-specific apis

---

js/interface.templates.js
js/libs.js
templates/interface/active-user.interface.hbs

requires https://github.com/Fliplet/fliplet-api/pull/2980

using more aggregation APIs

---

css/interface.css
interface.html
js/libs.js

progress text on load

---

css/interface.css
interface.html
js/libs.js

- adds a better loader (like the one shown when the theme compiles in studio)
- fixes some views that weren't displaying all numbers

UI Improvements and fixes

---

js/libs.js

Initial variable name was misleading

Corrects period unit to use ms instead of seconds

---

js/libs.js

https://github.com/Fliplet/fliplet-widget-analytics-report-provider/pull/21/commits/aa4730a70caad29caf04eff01cb92aced2735d0c is the primary change

Ensures end date is correct when aggregating counts

---

js/libs.js

Making use of moment.duration for calculations

Cleans up units with moment durations

---

interface.html

Ref. https://github.com/Fliplet/fliplet-studio/issues/4496

Label update for the full list of users

---

.eslintrc
.gitignore
js/interface.js
js/libs.js
package-lock.json

@sofiiakvasnevska 
Applied EsLint rules for the component
Using [this](https://www.npmjs.com/package/eslint-config-fliplet) EsLint config

Applied EsLint rules for the component

---

js/libs.js

@sofiiakvasnevska 
https://github.com/Fliplet/fliplet-studio/issues/5040
Allow user to load analytics provider in the IE11
Before
https://share.getcloudapp.com/E0uEkdxN
After
https://share.getcloudapp.com/ApuO415g

Allow user to load analytics provider in the IE11

---

js/interface.js

@sofiiakvasnevska
https://github.com/Fliplet/fliplet-studio/issues/6266
Added Fliplet.Widget.autosize(); on resize event. Also fixed parseInt typo. 
https://streamable.com/b63sam
@upplabs-alex-levchenko @YaroslavOvdii

Analytics container height will be updated on resize 

---

js/libs.js

ref https://github.com/Fliplet/fliplet-studio/issues/6399

[Fix] [Maintenance] Refactor of all tables to use server-side pagination and filtering

---

js/libs.js

ref https://github.com/Fliplet/fliplet-studio/issues/6414

[Fix] Server-side order (sort) on some tables

---

js/libs.js

As part of the ticket https://weboo.atlassian.net/browse/GD-351, and to be able to complete https://weboo.atlassian.net/browse/GD-362
- Adds GA tracking to the App Analytics provider

Added event tracking to app analytics provider

---

js/libs.js

Ref. https://weboo.atlassian.net/browse/ID-1358
Follows https://github.com/Fliplet/fliplet-widget-analytics-report-provider/pull/44

ID-1358 [Feat] Updated to use TD() function

---

js/libs.js

Ref. https://weboo.atlassian.net/browse/ID-1358
Follows https://github.com/Fliplet/fliplet-widget-analytics-report-provider/pull/44

ID-1358 [Fix] Only apply English locales

---

js/libs.js

Ref. https://weboo.atlassian.net/browse/ID-1716

ID-1716 [Fix] Ensure overlays are correctly resized after the log table is rendered

---

js/libs.js

Ref. https://weboo.atlassian.net/browse/ID-1717

ID-1717 [Maintenance] Prevent filters from sending too many API requests

---

interface.html
js/interface.templates.js
js/libs.js

@romanyosyfiv @inna-bieshulia 
OD-690 https://weboo.atlassian.net/browse/OD-690
**Problem:** Some phrases are written entirely in capital letters.
**Solution:** Only the first word starts with a capital letter.
@upplabs-alex-levchenko

OD-690 [Fix] Fixed capital letters to lowercase

---

js/libs.js

@romanyosyfiv @inna-bieshulia
OD-739 https://weboo.atlassian.net/browse/OD-739
@upplabs-alex-levchenko

OD-739 [Fix] Fixed spelling of words in uppercase

---

js/libs.js

Ref. https://weboo.atlassian.net/browse/ID-2560

ID-2560 [Fix] Correctly use "Last X days/months" options

---

.eslintrc
js/interface.js
js/interface.templates.js
js/libs.js
package-lock.json
package.json
templates/interface/app-metrics.interface.hbs

Ref. https://weboo.atlassian.net/browse/ID-3292
The `moment.duration().asDays()` method is used to convert the difference in time between the two dates to a duration in days. The result is not always an integer because of the variations in the lengths of months.

ID-3292 [Fix] Fix analytics consistency issue with app metrics

---

css/interface.css
interface.html
js/libs.js
js/view.js

https://weboo.atlassian.net/browse/ID-4211

ID-4211 [feat] technology details report

---

js/libs.js

https://weboo.atlassian.net/browse/ID-4453

ID-4453 [fix] loading analytics fallbacks errors

---

css/interface.css
interface.html
js/libs.js
js/view.js

- fixed exporting table data
- added fallbacks for no data;
-  revamped blocks layout;
-  disabled ordering non-orderable columns
https://weboo.atlassian.net/browse/ID-4471
https://weboo.atlassian.net/browse/ID-4468
https://weboo.atlassian.net/browse/ID-4470

ID-4471 [fix] exporting table data

---

js/libs.js

Component->`js/libs.js`
- Ensures correct active, new and returning devices are shown in analytics 
[ID-4522](https://weboo.atlassian.net/browse/ID-4522)
[ID-4522]: https://weboo.atlassian.net/browse/ID-4522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix/ID-4522 Ensures correct active, new and returning devices are shown in analytics 

---

js/libs.js

https://weboo.atlassian.net/browse/ID-4577

fix(ID-4577): added handle for unexpected error with statusText "OK" when exporting to CSV

---

js/libs.js

https://weboo.atlassian.net/browse/ID-4577

release/ID-4577: added handle for unexpected error with statusText "OK" when exporting to CSV

---

js/interface.js
js/libs.js

Ref. https://weboo.atlassian.net/browse/PR-7

PR-7 [Feat] Set custom date based on dates provided via the provider input
